### ISSUE TITLE
Job usage

### ISSUE THREAD

**Issue by rever96** [gilzoide/unity-update-manager#12]
Hi, first of all great code for handling the Unityy's update.

I was trying with the Job example in the readme https://github.com/gilzoide/unity-update-manager#updatetransformjobmanager--monobehaviour

And I'm getting this warning every time I goes in playmode:

```
Compilation was requested for method `UnityEngine.Jobs.IJobParallelForTransformExtensions+TransformParallelForLoopStruct`1[[Gilzoide.UpdateManager.Jobs.UpdateTransformJob`1[[MoveJob, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], Gilzoide.UpdateManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null::Execute(Gilzoide.UpdateManager.Jobs.UpdateTransformJob`1[[MoveJob, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]&, Gilzoide.UpdateManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|Unity.Jobs.LowLevel.Unsafe.JobRanges&, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)` but it is not a known Burst entry point. This may be because the [BurstCompile] method is defined in a generic class, and the generic class is not instantiated with concrete types anywhere in your code.
```

Second question, in the readme under features it's written `Job data may be modified from within jobs and fetched anytime`. Can you add an example usage?

**Comment by gilzoide** [comment]
> Hi, first of all great code for handling the Unity's update.

Thanks, I'm glad you liked it =]

> And I'm getting this warning every time I goes in playmode:

Yeah, so to be able to compile the job with Burst, you need to explicitly use the concrete type of the job struct, like so:
```cs
// Instead of this:
//   public class MyJobifiedBehaviour : AJobBehaviour<MoveJob>
// Use this:
public class MyJobifiedBehaviour : AJobBehaviour<MoveJob, UpdateTransformJob<MoveJob>>
{
    // ...
}
```
This is outlined [here](https://github.com/gilzoide/unity-update-manager/blob/75712d5d2d8f5b629c4a6012317ae05d8ea8e465/README.md?plain=1#L158-L159), but I agree that it is not that clear.
The job runs fine even without Burst compiling, as you might have tested, so it is not that much of a big deal.

I'm rethinking now that maybe there should be a separate type for Burst-enabled and non-Burst and we force people to always pass the second type parameter:
```cs
// Either use this for non-Burst jobs:
public class MyJobifiedBehaviour : AJobBehaviour<MoveJob, UpdateTransformJob<MoveJob>>
// Or this for Burst-enabled jobs:
public class MyJobifiedBehaviour : AJobBehaviour<MoveJob, BurstUpdateTransformJob<MoveJob>>
```
What do you think?

<hr/>

> Second question, in the readme under features it's written `Job data may be modified from within jobs and fetched anytime`. Can you add an example usage?

About this one, that's actually shown in the same example you quoted. [Here](https://github.com/gilzoide/unity-update-manager/blob/75712d5d2d8f5b629c4a6012317ae05d8ea8e465/README.md?plain=1#L152-L153) you can see the job setting the boolean flag to `true`, and [here](https://github.com/gilzoide/unity-update-manager/blob/75712d5d2d8f5b629c4a6012317ae05d8ea8e465/README.md?plain=1#L177-L180) we have some code in the `Start` method that accesses the most recent job data, after being transformed by the job that ran in the past frame.
You can add the same `Debug.Log("Something happened: " + currentData.SomethingHappened);` call before the `yield null;` line to see that it is initially `false`, than after one frame - and the job - runs, it gets updated to `true`.

**Comment by rever96** [comment]
> I'm rethinking now that maybe there should be a separate type for Burst-enabled and non-Burst and we force people to always pass the second type parameter

I think that way is cleaner.

<hr/>

> About this one, that's actually shown in the same example you quoted

Yeah I already saw that. I misundersood `Job data may be modified from within jobs and fetched anytime`: I thought I could change the data of the job after the job was created from outside the job. my bad.

Thanks for the fast reply

**Comment by gilzoide** [comment]
> I think that way is cleaner.

Alright, I agree. I'll make it happen for the next version, but it will most likely still accept the version with 1 type parameter to avoid a breaking existing projects that use this.

> I thought I could change the data of the job after the job was created from outside the job. my bad.

No problem. I did have an idea some time ago about how to make a variation of the `UpdateJobManager` that would call a sort of sychronization method, so that users could modify the job data in a safe moment where the job is not being run yet. But this is still an ideia and was not implemented yet. Say, what is your use-case for such functionality?

**Comment by rever96** [comment]
> but it will most likely still accept the version with 1 type parameter to avoid a breaking

Consider using the `[Obsolete("use 2param instead")]` tag on the older version

> what is your use-case for such functionality?

not a real one, I was playing with that classes to understand where and when to use it. xd In that specific case I was trying to change the direction of the job movement  after a while the job started

**Comment by gilzoide** [comment]
Hey @rever96 , I've added an implementation for job data synchronization, it is in the [rc-1.4.0](https://github.com/gilzoide/unity-update-manager/tree/rc-1.4.0) branch.

I haven't taken the time to document properly, but if you want to try it out, it's something in the lines of:
- Implement [IJobDataSynchronizer<>](https://github.com/gilzoide/unity-update-manager/blob/rc-1.4.0/Runtime/Jobs/IJobDataSynchronizer.cs) in your job provider
- Call [SynchronizeJobDataOnce](https://github.com/gilzoide/unity-update-manager/blob/rc-1.4.0/Runtime/Jobs/ITransformJobUpdatable.cs#L85-L93) whenever you want data synchronization to happen. The `SyncJobData` interface method will be called while no job is being executed, so it is safe to modify the job data actually used by the next job.
- You can also register your job provider to sync job data every frame using `myJobProvider.RegisterInManager(true)`.

As always, I'm open for feedback about the feature, API, implementation, anything, just open a new issue or discussion about it =]

<hr/>

> Consider using the [Obsolete("use 2param instead")] tag on the older version

That's right, I had forgotten about Obsolete. For now, I added the new `BurstUpdateJob<>` and `BurstUpdateTransformJob<>` structs, but maintained the version of `AJobBehaviour<>` with 1 type parameter, using non-Burst jobs by default. I think it doesn't hurt to use it as default and avoid requiring a second parameter, as Burst-enabled jobs need to be explicitly passed anyway.
